version: '3.4'

services:
  yarp.test.api:
    image: ${DOCKER_REGISTRY-}yarptestapi
    container_name: api
    build:
      context: .
      dockerfile: src/Yarp.Test.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    # ports:
    #   - 5000:8080
    #   - 5001:8081    
    networks:
      - proxybackend

  yarp.test.gateway:
    image: ${DOCKER_REGISTRY-}yarptestgateway
    container_name: gateway
    build:
      context: .
      dockerfile: src/Yarp.Test.Gateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 4000:8080
#      - 4001:8081 
    networks:
      - proxybackend

networks:
  proxybackend:
    name: proxybackend
    driver: bridge
